"""Public shared schemas preserved across architecture refactors."""

from shared.schemas.candidate import (
    CandidateEducation,
    CandidateExperience,
    CandidateProfile,
    CandidateProject,
    ResumeUploadResult,
    SkillEvidence,
)
from shared.schemas.auth import CurrentUser
from shared.schemas.decision import DecisionAction, InterviewDecision
from shared.schemas.evaluation import AnswerEvaluation, DifficultyDecision, EvaluationScore
from shared.schemas.graph_state import GraphError, InterviewGraphState, MemoryState, RAGChunk
from shared.schemas.interview import (
    AnswerSubmission,
    Difficulty,
    ExperienceLevel,
    InterviewConfig,
    InterviewMode,
    InterviewMemoryState,
    InterviewHistoryTurn,
    InterviewLanguage,
    InterviewPlan,
    InterviewQuestion,
    InterviewRound,
    InterviewSessionSummary,
    InterviewSessionStartRequest,
    InterviewSessionStartResponse,
    InterviewSessionState,
    InterviewStatus,
    InterviewStyle,
    InterviewerPersonality,
    InterviewTurn,
    InterviewTurnStatus,
    QuestionType,
    VoiceAnalytics,
)
from shared.schemas.job import JobAnalysisResult, JobRequirements
from shared.schemas.report import (
    FinalReport,
    HiringRecommendation,
    InterviewReport,
    LearningPlanItem,
    SkillAssessment,
    TopicScore,
)

__all__ = [
    "AnswerEvaluation",
    "AnswerSubmission",
    "CandidateEducation",
    "CandidateExperience",
    "CandidateProfile",
    "CandidateProject",
    "CurrentUser",
    "DecisionAction",
    "Difficulty",
    "DifficultyDecision",
    "EvaluationScore",
    "ExperienceLevel",
    "FinalReport",
    "GraphError",
    "HiringRecommendation",
    "InterviewConfig",
    "InterviewDecision",
    "InterviewGraphState",
    "InterviewHistoryTurn",
    "InterviewLanguage",
    "InterviewMode",
    "InterviewMemoryState",
    "InterviewPlan",
    "InterviewQuestion",
    "InterviewRound",
    "InterviewSessionSummary",
    "InterviewSessionStartRequest",
    "InterviewSessionStartResponse",
    "InterviewSessionState",
    "InterviewStatus",
    "InterviewReport",
    "InterviewStyle",
    "InterviewerPersonality",
    "InterviewTurn",
    "InterviewTurnStatus",
    "JobAnalysisResult",
    "JobRequirements",
    "LearningPlanItem",
    "MemoryState",
    "QuestionType",
    "VoiceAnalytics",
    "RAGChunk",
    "ResumeUploadResult",
    "SkillEvidence",
    "SkillAssessment",
    "TopicScore",
]
